import { createFileRoute } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { Bell, ChevronRight, CircleHelp, Download, FileText, LogOut, Plus, Search, Upload } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { lovable } from "@/integrations/lovable/index";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Toaster } from "@/components/ui/sonner";
import type { Database } from "@/integrations/supabase/types";
import { processDocumentDemo } from "@/lib/document-processing.functions";

type Case = Database["public"]["Tables"]["lc_applications"]["Row"];
type DemoCase = Database["public"]["Tables"]["demo_cases"]["Row"];
type Document = Database["public"]["Tables"]["lc_documents"]["Row"];
type Extraction = Database["public"]["Tables"]["extracted_fields"]["Row"];
type Discrepancy = Database["public"]["Tables"]["discrepancies"]["Row"];
type Clarification = Database["public"]["Tables"]["clarifications"]["Row"];
type Approval = Database["public"]["Tables"]["approvals"]["Row"];
type Audit = Database["public"]["Tables"]["audit_logs"]["Row"];
type Notification = Database["public"]["Tables"]["notifications"]["Row"];
type ComplianceFlag = Database["public"]["Tables"]["compliance_flags"]["Row"];
type TradeSetting = Database["public"]["Tables"]["tradeflow_settings"]["Row"];
type AdminUser = Database["public"]["Functions"]["list_tradeflow_users"]["Returns"][number];
type Role = Database["public"]["Enums"]["app_role"];
type DisplayCase = Pick<Case,"id"|"reference"|"applicant"|"beneficiary"|"amount"|"currency"|"application_type"|"validity"|"incoterms"|"special_instructions"|"stage"|"status"|"priority"|"created_at"> & {confidence?: number};
type DisplayField = { id?: string; field_name: string; field_value: string; confidence: number; source_document: string; reviewed_by?: string | null };

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "SG TradeFlow | LC Processing Platform" },
    { name: "description", content: "Secure customer and trade operations workspace for AI-assisted letter of credit processing." },
    { property: "og:title", content: "SG TradeFlow | LC Processing Platform" },
    { property: "og:description", content: "AI-assisted letter of credit processing with human review and approval." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ] }), component: TradeFlow,
});

const customerNav = ["Home","Applications","Documents","LC Status"];
const opsNav = ["Home","LC Requests","Extraction","Discrepancies","Approvals","Audit"];
const settingSections = [
  {key:"confidence_thresholds",label:"Confidence Thresholds",hint:"Stored for future analysis; demo fields use a fixed review indicator",defaultValue:{high:90,medium:75}},
  {key:"validation_rules",label:"Validation Rules",hint:"Stored for future validation; demo processing does not analyze file content",defaultValue:{enabled:false}},
  {key:"document_types",label:"Document Types",hint:"Recognised trade document types",defaultValue:{types:["LC Application Form","Commercial Invoice","Bill of Lading","Beneficiary Certificate","Signed Undertaking"]}},
  {key:"workflow_configuration",label:"Workflow Configuration",hint:"Stored preferences cannot override mandatory human approval controls",defaultValue:{manual_approval_required:true}},
  {key:"notification_templates",label:"Notification Templates",hint:"Stored for future delivery; email remains mock-only",defaultValue:{clarification:"Clarification requested",approval:"LC decision recorded"}},
] as const;
const stages = ["Application submitted","Document upload","AI extraction & validation","Discrepancy review","LC issuance"];
const formatMoney = (amount: number, currency: string) => `${currency} ${Number(amount).toLocaleString("en-US",{maximumFractionDigits:2})}`;
const date = (value: string) => new Date(value).toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"});
function tone(value: string) { const v=value.toLowerCase(); return v.includes("issu")||v.includes("resolv")||v.includes("upload")||v.includes("completed")||v.includes("reviewed") ? "positive" : v.includes("flag")||v.includes("reject")||v.includes("urgent") ? "critical" : v.includes("pending")||v.includes("clarif")||v.includes("approval")||v.includes("open") ? "warning" : "neutral"; }
function Status({value}:{value:string}) { return <span className={`trade-pill ${tone(value)}`}>{value}</span>; }
function Heading({title,subtitle,action}:{title:string,subtitle?:string,action?:React.ReactNode}) { return <div className="trade-heading"><div><div className="trade-kicker">LC Processing Platform</div><h1 className="trade-title">{title}</h1>{subtitle && <p className="trade-subtitle">{subtitle}</p>}</div>{action}</div>; }
function SearchBox({value,onChange,placeholder}:{value:string,onChange:(v:string)=>void,placeholder:string}) { return <label className="trade-search"><Search size={16}/><input aria-label="Search" value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>; }
function DataTable({heads,children}:{heads:string[],children:React.ReactNode}) { return <div className="trade-table-wrap"><table className="trade-table"><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }
function Empty({children}:{children:React.ReactNode}) {return <div className="trade-empty">{children}</div>}

function TradeFlow(){
  const [user,setUser]=useState<{id:string;email:string|undefined}|null>(null);
  const [role,setRole]=useState<Role|null>(null);
  const [name,setName]=useState("");
  const [ready,setReady]=useState(false);
  const [cases,setCases]=useState<DisplayCase[]>([]);
  const [tab,setTab]=useState("Home");
  const [mode,setMode]=useState<"customer"|"ops">("ops");
  const [selected,setSelected]=useState<string|null>(null);
  const [search,setSearch]=useState("");
  const [filter,setFilter]=useState("All stages");
  const [docs,setDocs]=useState<Document[]>([]);
  const [fields,setFields]=useState<Extraction[]>([]);
  const [discrepancies,setDiscrepancies]=useState<Discrepancy[]>([]);
  const [clarifications,setClarifications]=useState<Clarification[]>([]);
  const [approvals,setApprovals]=useState<Approval[]>([]);
  const [audit,setAudit]=useState<Audit[]>([]);
  const [notifications,setNotifications]=useState<Notification[]>([]);
  const [flags,setFlags]=useState<ComplianceFlag[]>([]);
  const [settings,setSettings]=useState<TradeSetting[]>([]);
  const [adminUsers,setAdminUsers]=useState<AdminUser[]>([]);
  const [adminSection,setAdminSection]=useState("Users");
  const [dialog,setDialog]=useState<"auth"|"new"|"clarify"|"respond"|"resolve"|"decision"|"compliance"|"flag"|null>(null);
  const [authMode,setAuthMode]=useState<"signin"|"signup">("signin");
  const [busy,setBusy]=useState(false);
  const [target,setTarget]=useState<string|null>(null);
  const [decision,setDecision]=useState<"Approved"|"Rejected">("Approved");
  const [complianceDecision,setComplianceDecision]=useState("Under Review");
  const [reason,setReason]=useState("");
  const [page,setPage]=useState(0);
  const fileRef=useRef<HTMLInputElement>(null);
  const isDemo=!user;
  const isStaff=role!==null&&role!=="customer";
  const canOfficer=role==="officer"||role==="admin";
  const canApprove=role==="approver"||role==="admin";
  const canCompliance=role==="compliance"||role==="admin";
  const selectedCase=cases.find(c=>c.id===selected)??null;

  const loadCases=useCallback(async(currentUser:{id:string}|null, currentRole:Role|null)=>{
    if(!currentUser){const {data,error}=await supabase.from("demo_cases").select("*").order("reference");if(error) toast.error(error.message);setCases((data??[]).map(c=>({...c,confidence:c.confidence})));return;}
    const q=supabase.from("lc_applications").select("*").order("created_at",{ascending:false});
    const {data,error}=await (currentRole==="customer"||!currentRole?q.eq("customer_id",currentUser.id):q);
    if(error) toast.error(error.message);setCases((data??[]) as DisplayCase[]);
  },[]);
  const loadDetails=useCallback(async(id:string)=>{
    const results=await Promise.all([
      supabase.from("lc_documents").select("*").eq("application_id",id).order("created_at",{ascending:false}),
      supabase.from("extracted_fields").select("*").eq("application_id",id),
      supabase.from("discrepancies").select("*").eq("application_id",id),
      supabase.from("clarifications").select("*").eq("application_id",id).order("created_at",{ascending:false}),
      supabase.from("approvals").select("*").eq("application_id",id).order("created_at",{ascending:false}),
      supabase.from("audit_logs").select("*").eq("application_id",id).order("created_at",{ascending:false}),
    ]);
    setDocs(results[0].data??[]);setFields(results[1].data??[]);setDiscrepancies(results[2].data??[]);setClarifications(results[3].data??[]);setApprovals(results[4].data??[]);setAudit(results[5].data??[]);
    results.forEach(r=>{if(r.error) toast.error(r.error.message)});
  },[]);
  const loadNotifications=useCallback(async()=>{const {data,error}=await supabase.from("notifications").select("*").order("created_at",{ascending:false}).limit(50);if(error)toast.error(error.message);else setNotifications(data??[])},[]);
  const loadFlags=useCallback(async()=>{const {data,error}=await supabase.from("compliance_flags").select("*").order("created_at",{ascending:false});if(error)toast.error(error.message);else setFlags(data??[])},[]);
  const loadAdmin=useCallback(async()=>{const [users,configuration]=await Promise.all([supabase.rpc("list_tradeflow_users"),supabase.from("tradeflow_settings").select("*")]);if(users.error)toast.error(users.error.message);else setAdminUsers(users.data??[]);if(configuration.error)toast.error(configuration.error.message);else setSettings(configuration.data??[])},[]);
  useEffect(()=>{let active=true;async function init(){const {data}=await supabase.auth.getUser();if(!active)return;const current=data.user;if(current){let {data:roles}=await supabase.from("user_roles").select("role").eq("user_id",current.id);if(!roles?.length){const metadata=current.user_metadata as {full_name?:string;organisation?:string};await supabase.rpc("register_customer",{_name:metadata.full_name||current.email?.split("@")[0]||"Customer",_organisation:metadata.organisation||""});({data:roles}=await supabase.from("user_roles").select("role").eq("user_id",current.id));}const r=roles?.[0]?.role??null;const {data:profile}=await supabase.from("profiles").select("full_name").eq("id",current.id).maybeSingle();if(!active)return;setUser({id:current.id,email:current.email});setRole(r);setName(profile?.full_name||current.email?.split("@")[0]||"Account");setMode(r==="customer"||!r?"customer":"ops");await loadCases(current,r);await loadNotifications();}else{await loadCases(null,null);}if(active)setReady(true)}init();return()=>{active=false};},[loadCases,loadNotifications]);
  useEffect(()=>{if(selected&&!isDemo)loadDetails(selected);else{setDocs([]);setFields([]);setDiscrepancies([]);setClarifications([]);setApprovals([]);setAudit([])}},[selected,isDemo,loadDetails]);
  useEffect(()=>{if(user)loadFlags();else setFlags([])},[user?.id,loadFlags]);
   const refresh=async()=>{await loadCases(user,role);if(selected&&!isDemo)await loadDetails(selected);if(user)await loadNotifications();if(canCompliance)await loadFlags()};
  const visible=useMemo(()=>cases.filter(c=>{
    const match=`${c.reference} ${c.applicant} ${c.beneficiary}`.toLowerCase().includes(search.toLowerCase());
    return match&&(filter==="All stages"||c.stage===filter);
  }),[cases,search,filter]);
  const list=visible.slice(page*8,page*8+8);
   const switchTab=(value:string)=>{setTab(value);setSelected(null);setPage(0);if(value==="Compliance Review")loadFlags();if(value==="Administration")loadAdmin()};
  async function handleAuth(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const form=new FormData(e.currentTarget);const email=String(form.get("email")||"").trim();const password=String(form.get("password")||"");try{
    if(authMode==="signup"){
      const fullName=String(form.get("fullName")||"").trim();const organisation=String(form.get("organisation")||"").trim();if(!fullName||!organisation)throw new Error("Please enter your name and organisation.");
      const {data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:fullName,organisation}}});if(error)throw error;
      if(data.session){const {error:profileError}=await supabase.rpc("register_customer",{_name:fullName,_organisation:organisation});if(profileError)throw profileError;}
      else {toast.success("Check your email to confirm your account, then sign in.");setAuthMode("signin");return;}
    }else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;}
    const {data:auth}=await supabase.auth.getUser();if(auth.user){const {data:roles}=await supabase.from("user_roles").select("role").eq("user_id",auth.user.id);let r=roles?.[0]?.role??null;if(!r&&authMode==="signup"){await supabase.rpc("register_customer",{_name:String(form.get("fullName")),_organisation:String(form.get("organisation"))});r="customer"}const {data:profile}=await supabase.from("profiles").select("full_name").eq("id",auth.user.id).maybeSingle();setUser({id:auth.user.id,email:auth.user.email});setRole(r);setName(profile?.full_name||auth.user.email?.split("@")[0]||"Account");setMode(r&&r!=="customer"?"ops":"customer");setSelected(null);setTab("Home");setDialog(null);await loadCases(auth.user,r);toast.success("Signed in successfully");}
  }catch(err){toast.error(err instanceof Error?err.message:"Sign in failed")}finally{setBusy(false)}}
  async function googleSignIn(){setBusy(true);try{const result=await lovable.auth.signInWithOAuth("google",{redirect_uri:window.location.origin});if(result.error)throw result.error;if(result.redirected)return;window.location.reload()}catch(err){toast.error(err instanceof Error?err.message:"Google sign in failed")}finally{setBusy(false)}}
   async function logout(){await supabase.auth.signOut();setUser(null);setRole(null);setNotifications([]);setName("");setMode("ops");setSelected(null);setTab("Home");await loadCases(null,null);toast.success("Signed out")}
  const ensureAuth=()=>{if(isDemo){setDialog("auth");return false}return true};
  async function createCase(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!user)return;setBusy(true);const f=new FormData(e.currentTarget);const {data,error}=await supabase.from("lc_applications").insert({customer_id:user.id,applicant:String(f.get("applicant")),beneficiary:String(f.get("beneficiary")),amount:Number(f.get("amount")),currency:String(f.get("currency")),validity:String(f.get("validity")),incoterms:String(f.get("incoterms")),special_instructions:String(f.get("instructions"))}).select().single();if(error)toast.error(error.message);else if(data){await supabase.from("audit_logs").insert({application_id:data.id,actor_id:user.id,action:"Application submitted",details:"Customer created an LC application"});toast.success("Application submitted");setDialog(null);setTab("Applications");setSelected(data.id);await loadCases(user,role)}setBusy(false)}
  async function uploadFile(file:File){if(!user||!selectedCase||isDemo)return;if(file.size>20*1024*1024){toast.error("File must be under 20 MB");return}if(!["application/pdf","image/png","image/jpeg","application/vnd.openxmlformats-officedocument.wordprocessingml.document"].includes(file.type)){toast.error("Use PDF, DOCX, JPG or PNG");return}setBusy(true);const id=crypto.randomUUID();const path=`${selectedCase.id}/${id}/1/${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;try{const upload=await supabase.storage.from("lc-documents").upload(path,file,{upsert:false});if(upload.error)throw upload.error;const {error}=await supabase.from("lc_documents").insert({id,application_id:selectedCase.id,uploaded_by:user.id,name:file.name,document_type:"Supporting document",storage_path:path,mime_type:file.type,size_bytes:file.size});if(error){await supabase.storage.from("lc-documents").remove([path]);throw error}await supabase.from("audit_logs").insert({application_id:selectedCase.id,actor_id:user.id,action:"Document uploaded",details:file.name});toast.success("Document uploaded securely");try{await processDocumentDemo({data:{documentId:id}});toast.success("DEMO AI MODE: form values queued for human review; file content was not analyzed.")}catch(processError){toast.error(processError instanceof Error?processError.message:"Demo processing failed; the document remains uploaded.")}await refresh()}catch(error){toast.error(error instanceof Error?error.message:"Upload failed")}finally{setBusy(false)}}
  async function openDoc(doc:Document,download=false){const {data,error}=await supabase.storage.from("lc-documents").createSignedUrl(doc.storage_path,60,{download});if(error)toast.error(error.message);else if(data?.signedUrl)window.open(data.signedUrl,"_blank","noopener,noreferrer")}
  async function act(action:string,id:string,payload?:string){if(!user||!selectedCase)return;setBusy(true);try{let error: {message:string}|null=null;
    if(action==="clarify")({error}=await supabase.from("clarifications").insert({application_id:selectedCase.id,question:payload??"",created_by:user.id}));
    if(action==="respond")({error}=await supabase.rpc("respond_clarification",{_id:id,_response:payload??""}));
    if(action==="resolve")({error}=await supabase.rpc("decide_discrepancy",{_id:id,_reason:payload??""}));
    if(action==="request")({error}=await supabase.rpc("request_approval",{_app:selectedCase.id}));
    if(action==="decide")({error}=await supabase.rpc("decide_approval",{_id:id,_decision:decision,_reason:payload??""}));
    if(action==="review")({error}=await supabase.rpc("mark_extraction_reviewed",{_id:id}));
    if(error)throw new Error(error.message);
    toast.success(action==="request"?"Sent for approval":"Decision recorded");setDialog(null);setReason("");await refresh();
  }catch(err){toast.error(err instanceof Error?err.message:"Action failed")}finally{setBusy(false)}}
  async function reviewCompliance(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!target)return;setBusy(true);try{const {error}=await supabase.rpc("review_compliance_flag",{_id:target,_decision:complianceDecision,_reason:reason.trim()});if(error)throw error;setDialog(null);setReason("");await loadFlags();toast.success("Compliance decision recorded")}catch(err){toast.error(err instanceof Error?err.message:"Review failed")}finally{setBusy(false)}}
  async function createFlag(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selectedCase||!user||!canCompliance)return;const form=new FormData(e.currentTarget);setBusy(true);try{const {error}=await supabase.from("compliance_flags").insert({application_id:selectedCase.id,screening_status:"Flagged",flag_reason:String(form.get("reason")).trim(),risk_priority:String(form.get("risk")),review_status:"Open"});if(error)throw error;setDialog(null);await loadFlags();toast.success("Flag recorded for human review")}catch(err){toast.error(err instanceof Error?err.message:"Could not record flag")}finally{setBusy(false)}}
  async function assignRole(id:string,newRole:Role){if(!window.confirm("Change this user's role?"))return;setBusy(true);try{const {error}=await supabase.rpc("assign_tradeflow_role",{_user:id,_role:newRole});if(error)throw error;await loadAdmin();toast.success("Role updated")}catch(err){toast.error(err instanceof Error?err.message:"Role change failed")}finally{setBusy(false)}}
  async function saveSetting(key:string,value:TradeSetting["value"]){setBusy(true);try{const {error}=await supabase.rpc("set_tradeflow_setting",{_key:key,_value:value});if(error)throw error;await loadAdmin();toast.success("Configuration saved")}catch(err){toast.error(err instanceof Error?err.message:"Configuration could not be saved")}finally{setBusy(false)}}
  function draft(){if(!selectedCase||selectedCase.status!=="Issued"){toast.error("A validated draft is available only after human approval.");return}const text=`SG TRADEFLOW — VALIDATED LC DRAFT\nReference: ${selectedCase.reference}\nApplicant: ${selectedCase.applicant}\nBeneficiary: ${selectedCase.beneficiary}\nAmount: ${formatMoney(selectedCase.amount,selectedCase.currency)}\nValidity: ${selectedCase.validity}\nIncoterms: ${selectedCase.incoterms}\nSpecial instructions: ${selectedCase.special_instructions}\n\nFor downstream review only. No SWIFT transmission has occurred.`;const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([text],{type:"text/plain"}));link.download=`${selectedCase.reference}-validated-draft.txt`;link.click();URL.revokeObjectURL(link.href)}
  const demoRows=cases.length;
  const openCount=cases.filter(c=>c.status!=="Issued"&&c.status!=="Rejected").length;
  const pendingCount=cases.filter(c=>c.status.includes("Approval")).length;
  function CaseRows({rows}:{rows:DisplayCase[]}){return <DataTable heads={["LC Reference","Customer / Applicant","Beneficiary","Amount","Stage","Status","Priority","Action"]}>{rows.map(c=><tr key={c.id}><td className="reference">{c.reference}</td><td><strong>{c.applicant}</strong></td><td>{c.beneficiary}</td><td>{formatMoney(c.amount,c.currency)}</td><td>{c.stage}</td><td><Status value={c.status}/></td><td><Status value={c.priority}/></td><td><Button variant="link" className="px-0" onClick={()=>setSelected(c.id)}>View <ChevronRight size={14}/></Button></td></tr>)}</DataTable>}
  function CaseList({home=false}:{home?:boolean}){return <><div className="trade-toolbar"><SearchBox value={search} onChange={v=>{setSearch(v);setPage(0)}} placeholder={mode==="ops"?"Search by LC reference, customer or beneficiary...":"Search your LC application, reference number..."}/><div className="trade-filters"><select aria-label="Filter by stage" className="trade-filter" value={filter} onChange={e=>{setFilter(e.target.value);setPage(0)}}><option>All stages</option>{stages.map(s=><option key={s}>{s}</option>)}<option>Compliance review</option></select></div></div>{visible.length?<><CaseRows rows={home?visible.slice(0,5):list}/>{!home&&visible.length>8&&<div className="trade-toolbar"><span className="trade-subtitle">Showing {page*8+1}–{Math.min((page+1)*8,visible.length)} of {visible.length}</span><div className="trade-actions"><Button variant="outline" size="sm" disabled={page===0} onClick={()=>setPage(page-1)}>Previous</Button><Button variant="outline" size="sm" disabled={(page+1)*8>=visible.length} onClick={()=>setPage(page+1)}>Next</Button></div></div>}</>:<Empty>No applications match your search.</Empty>}</>}
  function DemoNote(){return isDemo?<div className="trade-note trade-note-spaced"><strong>Presentation data</strong> — You are viewing example cases from the shared demonstration database. Sign in to submit an application or access private documents and decisions.</div>:null}
  function Detail(){if(!selectedCase)return null;const c=selectedCase;const demo=isDemo;const demoFields:DisplayField[]=[{field_name:"Applicant",field_value:c.applicant,confidence:97,source_document:"LC Application Form"},{field_name:"Beneficiary",field_value:c.beneficiary,confidence:95,source_document:"LC Application Form"},{field_name:"Amount",field_value:formatMoney(c.amount,c.currency),confidence:99,source_document:"Commercial Invoice"},{field_name:"Incoterms",field_value:c.incoterms,confidence:88,source_document:"Bill of Lading"},{field_name:"Validity",field_value:c.validity,confidence:74,source_document:"LC Application Form"}];const displayFields:DisplayField[]=demo?demoFields:fields;return <>
    <div className="trade-heading"><div><Button variant="link" className="px-0" onClick={()=>setSelected(null)}>← Back to {tab}</Button><h1 className="trade-title trade-title-detail">{c.reference}</h1><p className="trade-subtitle">{c.application_type} · {c.applicant}</p></div><Status value={c.status}/></div><DemoNote/>
    <div className="trade-section-head"><h2>LC Details</h2><div className="trade-actions"><Button variant="outline" size="sm" onClick={draft} disabled={c.status!=="Issued"}><Download/> Download LC Draft</Button>{(canOfficer||demo)&&<Button size="sm" onClick={()=>{if(ensureAuth()){setReason("");setDialog("clarify")}}}>Request Clarification</Button>}</div></div>
    <div className="trade-detail">{[["Applicant",c.applicant],["Beneficiary",c.beneficiary],["Amount",formatMoney(c.amount,c.currency)],["Validity",c.validity],["Incoterms",c.incoterms],["Special Instructions",c.special_instructions||"—"]].map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div>
    <div className="trade-section-head"><h2>Application progress</h2></div><div className="trade-steps">{stages.map((s,i)=>{const current=stages.indexOf(c.stage);const stageStatus=i<current?"Completed":i===current?c.status:"Pending";return <div className="trade-step" key={s}><span className="trade-step-index">{i+1}</span><div><strong>{s}</strong><small>{i===0?"Application received":i===1?"Supporting trade documents":i===2?"Classification, extraction and validation":i===3?"Human discrepancy review":"Human approval and draft"}</small></div><Status value={stageStatus}/><small>{i<=current?date(c.created_at):"—"}</small></div>})}</div>
    <div className="trade-section-head"><h2>My Documents</h2><Button variant="outline" size="sm" disabled={busy} onClick={()=>ensureAuth()&&fileRef.current?.click()}><Upload/> Upload document</Button><input ref={fileRef} type="file" accept=".pdf,.docx,.png,.jpg,.jpeg" hidden onChange={e=>{const file=e.target.files?.[0];if(file)uploadFile(file);e.target.value=""}}/></div>{docs.length?<DataTable heads={["Document","Type","Uploaded","Processing","Actions"]}>{docs.map(d=><tr key={d.id}><td><FileText size={14} className="inline mr-2"/>{d.name}</td><td>{d.document_type}</td><td>{date(d.created_at)}</td><td><Status value={d.processing_status}/></td><td><div className="trade-actions"><Button variant="link" className="px-0" onClick={()=>openDoc(d)}>View</Button><Button variant="link" className="px-0" onClick={()=>openDoc(d,true)}>Download</Button></div></td></tr>)}</DataTable>:<Empty>{demo?"Example documents are not available for download. Sign in to upload and view your own files.":"No documents uploaded yet."}</Empty>}
    <div className="trade-section-head"><h2>AI Extraction Results</h2><span className="trade-subtitle">Advisory results · review required</span></div>{!demo&&fields.some(f=>f.source_document.includes("DEMO AI MODE"))&&<div className="trade-note trade-note-spaced"><strong>DEMO AI MODE</strong> — These are submitted form values, not extracted from the document. Confidence is a review indicator, not an AI measurement. An officer must confirm every value.</div>}{displayFields.length?<DataTable heads={["Field","Extracted value","Confidence","Source document","Review"]}>{displayFields.map((f,i)=><tr key={f.id??i}><td><strong>{f.field_name}</strong></td><td>{f.field_value}</td><td><Status value={`${f.confidence}% ${f.confidence<80?"Low confidence":"confidence"}`}/></td><td>{f.source_document}</td><td>{f.id && !f.reviewed_by && canOfficer?<Button variant="link" className="px-0" onClick={()=>act("review",f.id??"")}>Review</Button>:f.reviewed_by?<Status value="Reviewed"/>:demo?"Example":"Awaiting review"}</td></tr>)}</DataTable>:<Empty>Extraction has not been completed. Uploaded documents await human review.</Empty>}
    <div className="trade-section-head"><h2>Discrepancy Review</h2></div>{(demo?[{id:"example-1",criterion:"Shipment date",document_value:"14 Oct 2026",application_value:"20 Oct 2026",status:"Open",rule_reference:"UCP 600 Article 14"},{id:"example-2",criterion:"Partial shipment",document_value:"Not mentioned",application_value:"Not allowed",status:"Open",rule_reference:"Confirmation required"}]:discrepancies).length?<><DataTable heads={["Criteria","Document value","LC application value","Rule / status","Action"]}>{(demo?[{id:"example-1",criterion:"Shipment date",document_value:"14 Oct 2026",application_value:"20 Oct 2026",status:"Open",rule_reference:"UCP 600 Article 14"},{id:"example-2",criterion:"Partial shipment",document_value:"Not mentioned",application_value:"Not allowed",status:"Open",rule_reference:"Confirmation required"}]:discrepancies).map(d=><tr key={d.id}><td>{d.criterion}</td><td>{d.document_value}</td><td>{d.application_value}</td><td><Status value={d.status}/><small className="block text-muted-foreground">{d.rule_reference}</small></td><td>{d.status==="Open"&&(canOfficer||demo)?<Button variant="link" className="px-0" onClick={()=>{if(ensureAuth()){setTarget(d.id);setDialog("resolve")}}}>Resolve</Button>:"—"}</td></tr>)}</DataTable><div className="trade-note trade-note-top"><strong>AI insight</strong> — Potential mismatches require an explicit operations decision. AI never resolves a discrepancy.</div></>:<Empty>No discrepancies recorded for this application.</Empty>}
    <div className="trade-section-head"><h2>Clarification requests</h2></div>{clarifications.length?<DataTable heads={["Question","Response","Status","Action"]}>{clarifications.map(q=><tr key={q.id}><td>{q.question}</td><td>{q.response||"—"}</td><td><Status value={q.status}/></td><td>{q.status==="Awaiting customer"&&role==="customer"?<Button variant="link" className="px-0" onClick={()=>{setTarget(q.id);setDialog("respond")}}>Respond</Button>:"—"}</td></tr>)}</DataTable>:<Empty>No clarification requests recorded.</Empty>}
    <div className="trade-section-head"><h2>Compliance review</h2>{canCompliance&&<Button variant="outline" size="sm" onClick={()=>setDialog("flag")}>Record flag</Button>}</div><div className="trade-note trade-note-spaced">TradeFlow surfaces compliance flags for review. Final compliance decisions remain with the authorized Compliance function.</div>{flags.filter(f=>f.application_id===c.id).length?<DataTable heads={["Screening","Flag reason","Priority","Review","Action"]}>{flags.filter(f=>f.application_id===c.id).map(f=><tr key={f.id}><td>{f.screening_status}</td><td>{f.flag_reason}</td><td><Status value={f.risk_priority}/></td><td><Status value={f.review_status}/></td><td>{canCompliance?<Button variant="link" onClick={()=>{setTarget(f.id);setReason("");setDialog("compliance")}}>Review</Button>:"—"}</td></tr>)}</DataTable>:<Empty>No compliance flags recorded.</Empty>}
    <div className="trade-section-head"><h2>Human approval</h2>{(canOfficer||demo)&&<Button variant="outline" size="sm" onClick={()=>ensureAuth()&&act("request",c.id)}>Send for approval</Button>}</div>{approvals.length?<DataTable heads={["Item","Status","Decision reason","Action"]}>{approvals.map(a=><tr key={a.id}><td>LC issuance — {c.reference}</td><td><Status value={a.decision}/></td><td>{a.reason||"—"}</td><td>{a.decision==="Pending"&&canApprove?<div className="trade-actions"><Button variant="link" className="px-0" onClick={()=>{setTarget(a.id);setDecision("Approved");setDialog("decision")}}>Approve</Button><Button variant="link" className="px-0" onClick={()=>{setTarget(a.id);setDecision("Rejected");setDialog("decision")}}>Reject</Button></div>:"—"}</td></tr>)}</DataTable>:<Empty>No approval requested. Documents, extraction review, discrepancies and clarifications must be completed first.</Empty>}
    <div className="trade-section-head"><h2>Activity history</h2></div>{audit.length?<DataTable heads={["Date","Action","Details"]}>{audit.map(a=><tr key={a.id}><td>{date(a.created_at)}</td><td>{a.action}</td><td>{a.details||"—"}</td></tr>)}</DataTable>:<Empty>{demo?"Sign in to view a private case’s activity history.":"No recorded activity yet."}</Empty>}
  </>}
  function Dashboard(){return <><Heading title={mode==="ops"?"LC Processing & Review":"My Trade Finance"} subtitle={mode==="ops"?"Review, validate and manage letter of credit requests.":"Track the status of your LC applications."} action={mode==="ops"?<Button onClick={()=>{if(ensureAuth())setDialog("new")}}><Plus/> New LC Intake</Button>:<Button onClick={()=>{if(ensureAuth())setDialog("new")}}><Plus/> New application</Button>}/><DemoNote/>{mode==="ops"?<><div className="trade-stats"><div className="trade-stat"><span>Open LC requests</span><strong>{openCount}</strong><small>Requiring operational attention</small></div><div className="trade-stat"><span>LCs in pipeline</span><strong>{demoRows}</strong><small>Across all processing stages</small></div><div className="trade-stat"><span>Pending approval</span><strong>{pendingCount}</strong><small>Awaiting an authorised decision</small></div></div><div className="trade-section-head"><h2>Recent LC requests</h2><Button variant="link" onClick={()=>switchTab("LC Requests")}>View all <ChevronRight/></Button></div><CaseList home/><div className="trade-section-head"><h2>Quick links</h2></div><div className="trade-actions"><Button variant="outline" onClick={()=>ensureAuth()&&setDialog("new")}>New LC Intake</Button><Button variant="outline" onClick={()=>switchTab("Approvals")}>My Approvals</Button><Button variant="outline" onClick={()=>switchTab("LC Requests")}>Active LCs</Button><Button variant="outline" onClick={()=>switchTab("Discrepancies")}>Discrepancy Queue</Button></div></>:<><div className="trade-stats"><div className="trade-stat"><span>My applications</span><strong>{demoRows}</strong><small>Letters of credit</small></div><div className="trade-stat"><span>In progress</span><strong>{openCount}</strong><small>Currently being processed</small></div><div className="trade-stat"><span>Issued</span><strong>{cases.filter(c=>c.status==="Issued").length}</strong><small>Ready for download</small></div></div><div className="trade-section-head"><h2>My applications</h2><Button variant="link" onClick={()=>switchTab("Applications")}>View all <ChevronRight/></Button></div><CaseList home/></>}</>}
  function QueuePage(){const title=tab==="Applications"?"My Applications":tab==="LC Requests"?"LC Requests":tab==="Extraction"?"AI Extraction Results":tab==="Discrepancies"?"Discrepancy Review":tab==="Approvals"?"Approvals":tab==="Documents"?"My Documents":tab==="LC Status"?"My LC Status":"Audit Trail";let shown=cases;if(tab==="Approvals")shown=cases.filter(c=>c.status.includes("Approval")||c.status==="Issued");if(tab==="Discrepancies")shown=cases.filter(c=>c.stage==="Discrepancy review"||c.status.includes("clarification"));if(tab==="Extraction")shown=cases.filter(c=>c.stage==="AI extraction & validation"||c.stage==="Discrepancy review");return <><Heading title={title} subtitle={tab==="Approvals"?"AI recommends. Final approval always rests with an authorised human reviewer.":tab==="Extraction"?"Review extracted values and confidence against source documents.":tab==="Documents"?"Choose an application to view and upload its secure documents.":tab==="Audit"?"Select a case to view its recorded history.":"Track and review letter of credit applications."} action={(tab==="Applications"||tab==="LC Requests")?<Button onClick={()=>ensureAuth()&&setDialog("new")}><Plus/> New LC Intake</Button>:undefined}/><DemoNote/>{tab==="Approvals"&&<div className="trade-note"><strong>Human decision required.</strong> Approval remains blocked until documents, low-confidence extraction, discrepancies and clarifications have been reviewed.</div>}{shown.length?<><div className="trade-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search by LC reference, customer or beneficiary..."/></div><CaseRows rows={shown.filter(c=>`${c.reference} ${c.applicant} ${c.beneficiary}`.toLowerCase().includes(search.toLowerCase()))}/></>:<Empty>No cases in this queue yet.</Empty>}</>}
  function NotificationPage(){return <><Heading title="Notifications" subtitle="Updates about your applications"/>{notifications.length?<DataTable heads={["Date","Update","Application","Status"]}>{notifications.map(n=><tr key={n.id}><td>{date(n.created_at)}</td><td><strong>{n.title}</strong><div>{n.body}</div></td><td>{cases.find(c=>c.id===n.application_id)?.reference??"—"}</td><td>{n.read_at?"Read":<Button variant="link" onClick={async()=>{const {error}=await supabase.from("notifications").update({read_at:new Date().toISOString()}).eq("id",n.id);if(error)toast.error(error.message);else await loadNotifications()}}>Mark read</Button>}</td></tr>)}</DataTable>:<Empty>No notifications yet.</Empty>}</>}
  function CompliancePage(){return <><Heading title="Compliance Review" subtitle="Human review of flagged applications"/><div className="trade-note trade-note-spaced">TradeFlow surfaces compliance flags for review. Final compliance decisions remain with the authorized Compliance function.</div>{flags.length?<DataTable heads={["LC","Applicant","Beneficiary","Screening","Flag reason","Priority","Review","Action"]}>{flags.map(f=>{const c=cases.find(item=>item.id===f.application_id);return <tr key={f.id}><td>{c?.reference??"—"}</td><td>{c?.applicant??"—"}</td><td>{c?.beneficiary??"—"}</td><td>{f.screening_status}</td><td>{f.flag_reason}</td><td><Status value={f.risk_priority}/></td><td><Status value={f.review_status}/></td><td><Button variant="link" onClick={()=>{setTarget(f.id);setReason("");setDialog("compliance")}}>Review</Button></td></tr>})}</DataTable>:<Empty>No compliance flags to review.</Empty>}</>}
  function AdminPage(){const section=settingSections.find(s=>s.label===adminSection);return <><Heading title="Administration" subtitle="Program and platform configuration"/><div className="trade-toolbar"><div className="trade-filters">{["Users","Roles",...settingSections.map(s=>s.label),"Audit Log"].map(s=><Button key={s} size="sm" variant={adminSection===s?"default":"outline"} onClick={()=>setAdminSection(s)}>{s}</Button>)}</div></div>{adminSection==="Users"||adminSection==="Roles"?<DataTable heads={["Name","Organisation","Role","Change role"]}>{adminUsers.map(u=><tr key={u.id}><td>{u.full_name||"—"}</td><td>{u.organisation||"—"}</td><td><Status value={u.role??"Unassigned"}/></td><td><select aria-label={`Role for ${u.full_name}`} className="trade-filter" value={u.role??"customer"} disabled={busy||u.id===user?.id} onChange={e=>assignRole(u.id,e.target.value as Role)}>{["customer","officer","approver","compliance","admin"].map(r=><option key={r}>{r}</option>)}</select></td></tr>)}</DataTable>:adminSection==="Audit Log"?<AdminAudit/>:section?<form className="trade-form" key={section.key} onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);try{const value=JSON.parse(String(form.get("value")));if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("Enter a JSON object");saveSetting(section.key,value)}catch(err){toast.error(err instanceof Error?err.message:"Invalid configuration")}}}><div className="trade-note"><strong>{section.label}</strong><div>{section.hint}</div></div><label>Configuration (JSON)<Textarea name="value" rows={8} defaultValue={JSON.stringify(settings.find(s=>s.key===section.key)?.value??section.defaultValue,null,2)} required/></label><Button type="submit" disabled={busy}>Save configuration</Button></form>:null}</>}
  function AdminAudit(){const [entries,setEntries]=useState<Audit[]>([]);useEffect(()=>{let mounted=true;supabase.from("audit_logs").select("*").order("created_at",{ascending:false}).limit(100).then(({data,error})=>{if(mounted){if(error)toast.error(error.message);else setEntries(data??[])}});return()=>{mounted=false}},[]);return entries.length?<DataTable heads={["Date","Case","Action","Details"]}>{entries.map(a=><tr key={a.id}><td>{date(a.created_at)}</td><td>{cases.find(c=>c.id===a.application_id)?.reference??"—"}</td><td>{a.action}</td><td>{a.details}</td></tr>)}</DataTable>:<Empty>No audit events available.</Empty>}
  return <div className="trade-shell"><header className="trade-top"><div className="trade-brand"><span className="trade-mark"/>SG TradeFlow{mode==="ops"&&<span className="text-muted-foreground font-normal">Ops</span>}</div><div className="trade-identity"><CircleHelp size={16}/>{user&&<Button variant="ghost" size="icon" title={`${notifications.filter(n=>!n.read_at).length} unread notifications`} aria-label="Notifications" onClick={()=>{setSelected(null);setTab("Notifications");loadNotifications()}}><Bell size={16}/></Button>}<span className="identity-name"><strong>{isDemo?"Presentation view":name}</strong>{role?` · ${role}`:""}</span>{user?<Button variant="ghost" size="icon" title="Log out" aria-label="Log out" onClick={logout}><LogOut/></Button>:<Button variant="outline" size="sm" onClick={()=>setDialog("auth")}>Sign in</Button>}</div></header><nav className="trade-nav" aria-label="Main navigation">{(mode==="ops"?[...opsNav,...(canCompliance?["Compliance Review"]:[]),...(role==="admin"?["Administration"]:[])]:customerNav).map(item=><Button key={item} variant="ghost" className={tab===item?"trade-nav-active":""} onClick={()=>switchTab(item)}>{item}</Button>)}</nav><main className="trade-main">{!ready?<Empty>Loading applications…</Empty>:<>{isDemo&&<div className="trade-toolbar trade-mode-toolbar"><div className="trade-segment" aria-label="Presentation workspace"><Button variant="ghost" className={mode==="customer"?"selected":""} onClick={()=>{setMode("customer");setTab("Home");setSelected(null)}}>Customer Portal</Button><Button variant="ghost" className={mode==="ops"?"selected":""} onClick={()=>{setMode("ops");setTab("Home");setSelected(null)}}>Trade Ops Workspace</Button></div><span className="trade-subtitle">Read-only presentation view</span></div>}{selectedCase?<Detail/>:tab==="Home"?<Dashboard/>:tab==="Notifications"?<NotificationPage/>:tab==="Compliance Review"&&canCompliance?<CompliancePage/>:tab==="Administration"&&role==="admin"?<AdminPage/>:<QueuePage/>}</>}</main><footer className="trade-footer"><span>© SG TradeFlow 2026</span><span>v1.0.0&nbsp;&nbsp;&nbsp; Accessibility&nbsp;&nbsp;&nbsp; Legal notices&nbsp;&nbsp;&nbsp; Contact</span></footer><Toaster richColors/>
  <Dialog open={dialog==="auth"} onOpenChange={open=>!open&&setDialog(null)}><DialogContent><DialogHeader><DialogTitle>{authMode==="signin"?"Sign in to SG TradeFlow":"Create customer account"}</DialogTitle><DialogDescription>Access your private letter of credit applications and documents.</DialogDescription></DialogHeader><form className="trade-form" onSubmit={handleAuth}>{authMode==="signup"&&<><label>Full name<Input name="fullName" required/></label><label>Organisation<Input name="organisation" required/></label></>}<label>Email<Input name="email" type="email" autoComplete="email" required/></label><label>Password<Input name="password" type="password" autoComplete={authMode==="signin"?"current-password":"new-password"} minLength={6} required/></label><Button type="submit" disabled={busy}>{busy?"Please wait…":authMode==="signin"?"Sign in":"Create account"}</Button></form><Button variant="outline" onClick={googleSignIn} disabled={busy}>Continue with Google</Button><Button variant="link" onClick={()=>setAuthMode(authMode==="signin"?"signup":"signin")}>{authMode==="signin"?"New customer? Create an account":"Already have an account? Sign in"}</Button></DialogContent></Dialog>
  <Dialog open={dialog==="new"} onOpenChange={open=>!open&&setDialog(null)}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>New LC application</DialogTitle><DialogDescription>Submit the application details before uploading supporting documents.</DialogDescription></DialogHeader><form className="trade-form" onSubmit={createCase}><label>Applicant organisation<Input name="applicant" required defaultValue={role==="customer"?"":""}/></label><label>Beneficiary<Input name="beneficiary" required/></label><div className="trade-form-grid"><label>Amount<Input name="amount" type="number" min="1" step="0.01" required/></label><label>Currency<select name="currency"><option>USD</option><option>EUR</option><option>GBP</option><option>INR</option></select></label></div><label>Validity<Input name="validity" placeholder="e.g. 45 days from shipment" required/></label><label>Incoterms<Input name="incoterms" placeholder="e.g. FOB Shanghai" required/></label><label>Special instructions<Textarea name="instructions"/></label><DialogFooter><Button type="submit" disabled={busy}>Submit application</Button></DialogFooter></form></DialogContent></Dialog>
  <Dialog open={dialog==="clarify"||dialog==="respond"||dialog==="resolve"||dialog==="decision"} onOpenChange={open=>!open&&setDialog(null)}><DialogContent><DialogHeader><DialogTitle>{dialog==="clarify"?"Request clarification":dialog==="respond"?"Respond to clarification":dialog==="resolve"?"Resolve discrepancy":`${decision} LC issuance`}</DialogTitle><DialogDescription>{dialog==="decision"?"Your decision is recorded with your identity and timestamp. AI cannot approve an LC.":"This action is recorded in the application history."}</DialogDescription></DialogHeader><form className="trade-form" onSubmit={e=>{e.preventDefault();const action=dialog==="clarify"?"clarify":dialog==="respond"?"respond":dialog==="resolve"?"resolve":"decide";act(action,target??"",reason)}}><label>{dialog==="clarify"?"Question for customer":dialog==="respond"?"Your response":"Decision reason"}<Textarea required minLength={3} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Enter details..."/></label><DialogFooter><Button type="submit" disabled={busy}>{busy?"Saving…":"Confirm"}</Button></DialogFooter></form></DialogContent></Dialog>
  <Dialog open={dialog==="compliance"} onOpenChange={open=>!open&&setDialog(null)}><DialogContent><DialogHeader><DialogTitle>Compliance decision</DialogTitle><DialogDescription>Only an authorized human reviewer can clear or escalate this flag. A reason is required.</DialogDescription></DialogHeader><form className="trade-form" onSubmit={reviewCompliance}><label>Decision<select value={complianceDecision} onChange={e=>setComplianceDecision(e.target.value)}><option>Under Review</option><option>Cleared</option><option>Escalated</option></select></label><label>Reason<Textarea required minLength={3} value={reason} onChange={e=>setReason(e.target.value)}/></label><Button type="submit" disabled={busy}>Record decision</Button></form></DialogContent></Dialog>
  <Dialog open={dialog==="flag"} onOpenChange={open=>!open&&setDialog(null)}><DialogContent><DialogHeader><DialogTitle>Record compliance flag</DialogTitle><DialogDescription>This is a manual flag, not automated sanctions screening.</DialogDescription></DialogHeader><form className="trade-form" onSubmit={createFlag}><label>Flag reason<Textarea name="reason" required minLength={3}/></label><label>Risk priority<select name="risk"><option>Normal</option><option>High</option><option>Urgent</option></select></label><Button type="submit" disabled={busy}>Record flag</Button></form></DialogContent></Dialog>
  </div>;
}
