CREATE TYPE public.app_role AS ENUM ('customer','officer','approver','compliance','admin');
CREATE TABLE public.profiles (id uuid PRIMARY KEY, full_name text NOT NULL DEFAULT '', organisation text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE ON public.profiles TO authenticated; GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own profile read" ON public.profiles FOR SELECT TO authenticated USING (id = auth.uid());
CREATE POLICY "own profile insert" ON public.profiles FOR INSERT TO authenticated WITH CHECK (id = auth.uid());
CREATE POLICY "own profile update" ON public.profiles FOR UPDATE TO authenticated USING (id = auth.uid()) WITH CHECK (id = auth.uid());
CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, role public.app_role NOT NULL, UNIQUE(user_id,role));
GRANT SELECT ON public.user_roles TO authenticated; GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "read own role" ON public.user_roles FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE FUNCTION public.has_role(_user_id uuid, _role public.app_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role) $$;
GRANT EXECUTE ON FUNCTION public.has_role(uuid,public.app_role) TO authenticated;
CREATE FUNCTION public.is_staff(_user_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT public.has_role(_user_id,'officer') OR public.has_role(_user_id,'approver') OR public.has_role(_user_id,'compliance') OR public.has_role(_user_id,'admin') $$;
GRANT EXECUTE ON FUNCTION public.is_staff(uuid) TO authenticated;
CREATE TABLE public.lc_applications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), reference text UNIQUE NOT NULL DEFAULT ('LC-' || to_char(now(),'YYYY') || '-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,8))), customer_id uuid, applicant text NOT NULL, beneficiary text NOT NULL, amount numeric(18,2) NOT NULL CHECK(amount > 0), currency text NOT NULL DEFAULT 'USD', application_type text NOT NULL DEFAULT 'Import Letter of Credit', validity text NOT NULL DEFAULT '', incoterms text NOT NULL DEFAULT '', special_instructions text NOT NULL DEFAULT '', stage text NOT NULL DEFAULT 'Application submitted', status text NOT NULL DEFAULT 'Submitted', priority text NOT NULL DEFAULT 'Normal', assigned_officer text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE ON public.lc_applications TO authenticated; GRANT ALL ON public.lc_applications TO service_role;
ALTER TABLE public.lc_applications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "customer or staff read applications" ON public.lc_applications FOR SELECT TO authenticated USING (customer_id = auth.uid() OR public.is_staff(auth.uid()));
CREATE POLICY "customer create own application" ON public.lc_applications FOR INSERT TO authenticated WITH CHECK (customer_id = auth.uid() AND status = 'Submitted' AND stage = 'Application submitted');
CREATE POLICY "staff update applications" ON public.lc_applications FOR UPDATE TO authenticated USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));
CREATE TABLE public.lc_documents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), application_id uuid NOT NULL REFERENCES public.lc_applications(id) ON DELETE CASCADE, uploaded_by uuid NOT NULL, name text NOT NULL, document_type text NOT NULL DEFAULT 'Supporting document', storage_path text NOT NULL, mime_type text NOT NULL, size_bytes bigint NOT NULL, processing_status text NOT NULL DEFAULT 'Pending', created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE ON public.lc_documents TO authenticated; GRANT ALL ON public.lc_documents TO service_role;
ALTER TABLE public.lc_documents ENABLE ROW LEVEL SECURITY;
CREATE POLICY "application document read" ON public.lc_documents FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.lc_applications a WHERE a.id=application_id AND (a.customer_id=auth.uid() OR public.is_staff(auth.uid()))));
CREATE POLICY "application document upload" ON public.lc_documents FOR INSERT TO authenticated WITH CHECK (uploaded_by=auth.uid() AND EXISTS(SELECT 1 FROM public.lc_applications a WHERE a.id=application_id AND (a.customer_id=auth.uid() OR public.is_staff(auth.uid()))));
CREATE POLICY "staff document update" ON public.lc_documents FOR UPDATE TO authenticated USING (public.is_staff(auth.uid()));
CREATE TABLE public.extracted_fields (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), application_id uuid NOT NULL REFERENCES public.lc_applications(id) ON DELETE CASCADE, field_name text NOT NULL, field_value text NOT NULL, confidence integer NOT NULL CHECK(confidence BETWEEN 0 AND 100), source_document text NOT NULL DEFAULT '', reviewed_by uuid, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE ON public.extracted_fields TO authenticated; GRANT ALL ON public.extracted_fields TO service_role;
ALTER TABLE public.extracted_fields ENABLE ROW LEVEL SECURITY;
CREATE POLICY "extractions read" ON public.extracted_fields FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.lc_applications a WHERE a.id=application_id AND (a.customer_id=auth.uid() OR public.is_staff(auth.uid()))));
CREATE POLICY "staff extraction insert" ON public.extracted_fields FOR INSERT TO authenticated WITH CHECK (public.is_staff(auth.uid()));
CREATE POLICY "staff extraction update" ON public.extracted_fields FOR UPDATE TO authenticated USING (public.is_staff(auth.uid()));
CREATE TABLE public.discrepancies (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), application_id uuid NOT NULL REFERENCES public.lc_applications(id) ON DELETE CASCADE, criterion text NOT NULL, document_value text NOT NULL DEFAULT '', application_value text NOT NULL DEFAULT '', rule_reference text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'Open', resolution_reason text, resolved_by uuid, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE ON public.discrepancies TO authenticated; GRANT ALL ON public.discrepancies TO service_role;
ALTER TABLE public.discrepancies ENABLE ROW LEVEL SECURITY;
CREATE POLICY "discrepancies read" ON public.discrepancies FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.lc_applications a WHERE a.id=application_id AND (a.customer_id=auth.uid() OR public.is_staff(auth.uid()))));
CREATE POLICY "staff discrepancy insert" ON public.discrepancies FOR INSERT TO authenticated WITH CHECK (public.is_staff(auth.uid()));
CREATE POLICY "staff discrepancy update" ON public.discrepancies FOR UPDATE TO authenticated USING (public.is_staff(auth.uid()) AND resolved_by=auth.uid()) WITH CHECK (public.is_staff(auth.uid()) AND resolved_by=auth.uid() AND length(coalesce(resolution_reason,'')) > 0);
CREATE TABLE public.clarifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), application_id uuid NOT NULL REFERENCES public.lc_applications(id) ON DELETE CASCADE, question text NOT NULL, response text, status text NOT NULL DEFAULT 'Awaiting customer', created_by uuid, responded_by uuid, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE ON public.clarifications TO authenticated; GRANT ALL ON public.clarifications TO service_role;
ALTER TABLE public.clarifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "clarifications read" ON public.clarifications FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.lc_applications a WHERE a.id=application_id AND (a.customer_id=auth.uid() OR public.is_staff(auth.uid()))));
CREATE POLICY "staff clarification create" ON public.clarifications FOR INSERT TO authenticated WITH CHECK (public.is_staff(auth.uid()) AND created_by=auth.uid());
CREATE POLICY "customer clarification respond" ON public.clarifications FOR UPDATE TO authenticated USING (EXISTS(SELECT 1 FROM public.lc_applications a WHERE a.id=application_id AND a.customer_id=auth.uid()) AND status='Awaiting customer') WITH CHECK (responded_by=auth.uid() AND status='Responded' AND length(coalesce(response,''))>0);
CREATE TABLE public.approvals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), application_id uuid NOT NULL REFERENCES public.lc_applications(id) ON DELETE CASCADE, decision text NOT NULL DEFAULT 'Pending', reason text, decided_by uuid, created_at timestamptz NOT NULL DEFAULT now(), decided_at timestamptz);
GRANT SELECT, INSERT, UPDATE ON public.approvals TO authenticated; GRANT ALL ON public.approvals TO service_role;
ALTER TABLE public.approvals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "approval read" ON public.approvals FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.lc_applications a WHERE a.id=application_id AND (a.customer_id=auth.uid() OR public.is_staff(auth.uid()))));
CREATE POLICY "staff approval request" ON public.approvals FOR INSERT TO authenticated WITH CHECK (public.has_role(auth.uid(),'officer') AND decision='Pending' AND decided_by IS NULL);
CREATE POLICY "approver decision" ON public.approvals FOR UPDATE TO authenticated USING (public.has_role(auth.uid(),'approver') AND decision='Pending') WITH CHECK (public.has_role(auth.uid(),'approver') AND decided_by=auth.uid() AND decision IN ('Approved','Rejected') AND decided_at IS NOT NULL AND length(coalesce(reason,''))>0);
CREATE TABLE public.audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), application_id uuid REFERENCES public.lc_applications(id) ON DELETE CASCADE, actor_id uuid, action text NOT NULL, details text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT ON public.audit_logs TO authenticated; GRANT ALL ON public.audit_logs TO service_role;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "audit read" ON public.audit_logs FOR SELECT TO authenticated USING (application_id IS NOT NULL AND EXISTS(SELECT 1 FROM public.lc_applications a WHERE a.id=application_id AND (a.customer_id=auth.uid() OR public.is_staff(auth.uid()))));
CREATE POLICY "audit insert own" ON public.audit_logs FOR INSERT TO authenticated WITH CHECK (actor_id=auth.uid() AND application_id IS NOT NULL AND EXISTS(SELECT 1 FROM public.lc_applications a WHERE a.id=application_id AND (a.customer_id=auth.uid() OR public.is_staff(auth.uid()))));
CREATE TABLE public.demo_cases (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), reference text UNIQUE NOT NULL, applicant text NOT NULL, beneficiary text NOT NULL, amount numeric NOT NULL, currency text NOT NULL, application_type text NOT NULL, validity text NOT NULL, incoterms text NOT NULL, special_instructions text NOT NULL, stage text NOT NULL, status text NOT NULL, priority text NOT NULL, confidence integer NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.demo_cases TO anon, authenticated; GRANT ALL ON public.demo_cases TO service_role;
ALTER TABLE public.demo_cases ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public demonstration cases" ON public.demo_cases FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "private document upload" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id='lc-documents' AND (storage.foldername(name))[1] IN (SELECT id::text FROM public.lc_applications WHERE customer_id=auth.uid() OR public.is_staff(auth.uid())));
CREATE POLICY "private document read" ON storage.objects FOR SELECT TO authenticated USING (bucket_id='lc-documents' AND (storage.foldername(name))[1] IN (SELECT id::text FROM public.lc_applications WHERE customer_id=auth.uid() OR public.is_staff(auth.uid())));